#!/bin/bash
#https://wiki.archlinux.org/

#mirrors
sed -i -e '1iServer = http://mirrors.163.com/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
echo -e "[archlinuxcn]\nServer = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/\$arch\n" >> /etc/pacman.conf

#time
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
yes | pacman -S ntp
ntpdate -u ntp.api.bz #update time from network
hwclock --systohc

yes | pacman -Sy
yes | pacman -S archlinuxcn-keyring

#env
#uncomment /etc/locale.gen en_US.UTF-8
#show chinese in console
echo "zh_CN.GBK GBK" >> /etc/locale.gen
echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "arch" > /etc/hostname
echo -e "127.0.0.1	localhost\n::1		localhost" > /etc/hosts

#user
echo "set root password"
passwd
echo "add general user"
read generaluser
useradd -m $generaluser
echo "set general user password"
passwd $generaluser

#grub
yes | pacman -S grub
echo "set grub-install disk, example input /dev/sdb"
read diskn
grub-install --target=i386-pc $diskn
grub-mkconfig -o /boot/grub/grub.cfg

#network
yes | pacman -S networkmanager
systemctl enable NetworkManager
#yes | pacman -S wpa_supplicant
#connect wifi
nmcli device wifi connect ssidName password 12345678

#rc.local
yes | pacman -S systemd-rc-local
systemctl enable rc-local
cp ./rc.local /etc/

#xorg
yes | pacman -S xorg-server
yes | pacman -S xorg-apps
yes | pacman -S xf86-video-intel

#kde
yes | pacman -S plasma-meta
#yes | pacman -S kde-applications-meta
yes | pacman -S sddm
systemctl enable sddm

#input method
#yes | pacman -S fcitx-sogoupinyin
#yes | pacman -S fcitx-im
#yes | pacman -S fcitx-configtool
yes | pacman -S fcitx5-im
yes | pacman -S fcitx5-chinese-addons
yes | pacman -S fcitx5-pinyin-zhwiki

echo -e "#fcitx\n
export INPUT_METHOD  DEFAULT=fcitx\n
export GTK_IM_MODULE DEFAULT=fcitx\n
export GTK_IM_MODULE DEFAULT=fcitx\n
export XMODIFIERS    DEFAULT=\@im=fcitx\n
export XIM_PROGRAM=fcitx\n
export XIM=fcitx\n
export SIM_PROGRAM=fcitx\n
export XMODIFIERS=fcitx\n
export GTK_IM_MODULE=fcitx\n
export QT_IM_MODULE=fcitx\n" >> /etc/profile

yes | pacman -S wqy-bitmapfont
yes | pacman -S wqy-microhei
yes | pacman -S wqy-microhei-lite
yes | pacman -S wqy-zenhei
yes | pacman -S wqy-microhei-kr-patched

#most used software
#yes | pacman -S bash-completion
yes | pacman -S htop
yes | pacman -S bashtop
yes | pacman -S tmux
yes | pacman -S openssh
yes | pacman -S mlocate
yes | pacman -S latte-dock
yes | pacman -S shadowsocks
yes | pacman -S python-pip
pip install web.py==0.40-dev1 -i https://pypi.tuna.tsinghua.edu.cn/simple
mkdir /root/.pip
echo -e "[global]\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple\n[install]\ntrusted-host=pypi.tuna.tsinghua.edu.cn" > /root/.pip/pip.conf
echo "SUBSYSTEM==“usb”,ATTR{idVendor}==“18d1”,MODE=“0666”" > /etc/udev/rules.d/51-android.rules

#dns
echo -e "# Generated by wzl\nsearch wr\nnameserver 8.8.8.8\nnameserver 223.5.5.5\nnameserver 219.141.140.10" > /etc/resolv.conf
chattr +i /etc/resolv.conf
